### ISSUE TITLE
Re-training on clustering pseudo-labels

### ISSUE THREAD

**Issue by AruniRC** [yl-1993/learn-to-cluster#12]
Hi,

Could you please share more details about the re-training on pseudo-labels (Sec 4.2.2 of your paper) ?

When you are re-training the network on the clustering labels:

1. Do you start from the baseline recognition network (trained on labeled data) and *fine-tune* or start from *scratch* with labeled and pseudo-labeled data?
2. The pseudo-labeled data from clustering would have a lot of noise (overestimating the number of classes, etc.) -- do you train using alternate batches of labeled + pseudo-labeled data, or just train using default options?
3. Do you remove very small clusters, or place some threshold on the IoU or IoP of the clusters that are used as pseudo-labels (i.e., remove clusters with low IoU scores etc. because they could be noisy) ?

(nice work btw!)

**Comment by yl-1993** [comment]
@AruniRC Sorry for the late reply. Here are some more detailed settings that may help:
1. In order to avoid the influence of some fine-tuning tricks, we train from *scratch* in a multitask manner. Specifically, we take labeled and pseudo-labeled data as two branches, which shares all layers except the last classifier. You can checkout [this repo](https://github.com/XiaohangZhan/face_recognition_framework) for more details.
2. The training is conducted in multitask manner, i.e., the number of labeled data and pseudo-labeled data in each batch is equal. (Do I understand the question correctly?)
3. Good question and Yes. We study the influence of small clusters in our supplementary. For example, removing cluster less than 5 samples, removing cluster with IoP score less than 0.5. 

Thanks a lot for reproducing our work.

**Comment by AruniRC** [comment]
yes, that makes sense. thank you for the clarifications.
