### ISSUE TITLE
How to get IOP score for each proposal?

### ISSUE THREAD

**Issue by eezxuan** [yl-1993/learn-to-cluster#24]
How to get IOP predict value for each proposal?
Is the output_prob of model in test_cluster_det contain IOP prediction score?
I checked the code about the train code for GCN-D，but only found iou signal in line 69 of cluster_det_processor.py

Thanks very much

**Comment by yl-1993** [comment]
@eezxuan This repo currently only contains the IoU prediction, as it has not included GCN-S yet.
To get the IoP prediction, you can either (1) replace IoU with IoP or (2) train with both IoU and IoP. Both solutions require small modification on the code.

Specifically, for solution (1), when preparing the ground-truth for each proposal, we only need to modify this [line](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/datasets/cluster_det_processor.py#L38) to compute IoP instead of IoU.
For solution (2), in addition to the ground-truth preparation, we need to modify the [network](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/models/dsgcn.py#L129) to predict IoU and IoP with two fc layers respectively.

**Comment by yl-1993** [comment]
@eezxuan We have added the IoP prediction. To decouple IoU and IoP for better illustration, we implement solution (1) as discussed above. Feel free to have a try. :-)

**Comment by eezxuan** [comment]
Thank very much.

eezxuan

2020-04-14 


NELIVA




发件人：Lei Yang <notifications@github.com>
发送时间：2020-04-14 21:53
主题：Re: [yl-1993/learn-to-cluster] How to get IOP score for each proposal? (#24)
收件人："yl-1993/learn-to-cluster"<learn-to-cluster@noreply.github.com>
抄送："eezxuan"<eezxuan@163.com>,"Mention"<mention@noreply.github.com>

@eezxuan We have added the IoP prediction. To decouple IoU and IoP for better illustration, we implement solution (1) as discussed above. Feel free to have a try. :-)

**Comment by Dyfine** [comment]
Hello @yl-1993 
Thanks for your great work and project.
Currently I also try solution (1) to train the GCN-D for getting the IoP score and I find a small problem. In [`train.py`](https://github.com/yl-1993/learn-to-cluster/blob/master/dsgcn/train.py#L16), since the `build_dataset` function only gets `cfg.train_data` as input, the `det_label` attr is always missing, and the default value 'iou' is used. In this way, setting `det_label` to 'iop' in `train_cluster_det_iop_ms1m.sh` doesn't change the training target to IoP score and the target is still the IoU score. And to solve this problem, I add the following line
`setattr(cfg.train_data, 'det_label', cfg.det_label)`
before sending `cfg.train_data` into `build_dataset` function, which works for me.

**Comment by yl-1993** [comment]
@Dyfine Good catch! Do you want to create a PR for this?

**Comment by Dyfine** [comment]
Hi @yl-1993 
I just create a PR for this modification. I am sorry that I am not very familiar with the PR steps and please inform me if i did something wrong.

**Comment by yl-1993** [comment]
@Dyfine Thanks. It looks good to me and I have merged it into the master branch.
