### ISSUE TITLE
make gcn-v to very large scale dataset

### ISSUE THREAD

**Issue by tranorrepository** [yl-1993/learn-to-cluster#54]
hi, Lei Yang, in your paper, you write "Empirically, a 1-layer GCN takes 37G CPU Ram and 92s with 16 CPU on a graph with 5.2M vertices for inference", how do you make it?

**Comment by yl-1993** [comment]
Hi @tranorrepository , sorry for the late reply. For settings as large as 5.2M, we use CPU instead of GPU for GCN inference, as the memory demand will exceed the GPU memory. Actually, the bottleneck of the whole clustering procedure lies in the KNN construction, where we use faiss-gpu for acceleration.
